---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-inventory-worker-deployment
  namespace: kafkaworker
  labels:
    app: app-inventory-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-inventory-worker
  template:
    metadata:
      name: app-inventory-worker
      labels:
        app: app-inventory-worker
    spec:
      containers:
        - name: app-inventory-worker
          image: ivantipartners/elastic-indexer:117.0.0-2.production
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /actuator/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /actuator/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          env:
            - name: INDEXER_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: indexer.name
            - name: KAFKA_WORKER_GROUPID
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: kafka.worker.groupid
            - name: KAFKA_WORKER_TOPICS
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: kafka.worker.topics
            - name: KAFKA_WORKER_FAILEDTOPIC
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: kafka.worker.failedtopic
            - name: KAFKA_WORKER_RETRYFAILEDTOPIC
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: kafka.worker.retryfailedtopic
            - name: KAFKA_WORKER_ALIASNAMES
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: kafka.worker.aliasnames
            - name: KAFKA_SSL_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: kafka.ssl.enabled
            - name: JAVA_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: java.opts
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: kafka.hosts
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: db.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-inventory-worker-secret
                  key: db.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-inventory-worker-secret
                  key: db.password
            - name: ELASTICSEARCH_URL
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: es.url
            - name: KAFKA_WORKER_MESSAGETOINDEXTYPES
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: kafka.worker.messagetoindextypes
            - name: ZOOKEEPER_LIST
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: zookeeper.hosts
            - name: prefix
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: prefix
            - name: EsClusterNumberOfReplicas
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: es.replicas.number
            - name: reindex_kafka_topic_name
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: reindex.kafka.topic.name
            - name: reindex_es_index_name
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: reindex.es.index.name
            - name: CUSTOMATTRIBUTETRANSFORMATION_DEVICEINDEX_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: app-inventory-worker-configmap
                  key: customattributetransformation.deviceindex.enabled
          volumeMounts:
            - name: nfs-share-app-inventory-worker
              mountPath: /mobileiron.com/data/app-inventory-worker/debug/
      volumes:
        - name: nfs-share-app-inventory-worker
          persistentVolumeClaim:
            claimName: nfs-pvc-app-inventory-worker
      imagePullSecrets:
        - name: docker-hub-secret-kafkaworker
