---
apiVersion: v1
kind: Secret
metadata:
  name: dbmanager-secret
  namespace: dbmanager
type: Opaque
data:
  # BASE64 encoded
  db.password: "cG9sYXJpczEyMw==" # polaris123
  rpt.password: "cG9sYXJpczEyMw==" # polaris123
