---
apiVersion: v1
kind: ConfigMap
metadata:
  name: debezium-configmap
data:
  kafka.hosts: "kafka-0.cluster.datasvcs:9092,kafka-1.cluster.datasvcs:9092,kafka-2.cluster.datasvcs:9092"
  java.opts: "-Xmx1g -Xms1g -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/mobileiron.com/data/debezium/debug"
  db.host: "postgres.cluster.datasvcs"
  db.port: "5432"
  db.name: "polaris"
  db.sslmode: "disable"
  status.storage.replication.factor: "3"
  config.storage.replication.factor: "3"
  offset.storage.replication.factor: "3"
  config.storage.topic: "my-connect-configs"
  offset.storage.topic: "my-connect-offsets"
  offset.flush.interval: "20000"
  offset.flush.timeout: "40000"
  ps1: 'debezium@\h \W]\$'
  kafka.ssl.enabled: "false"
  enabled.publication.creation: "false"
