---
apiVersion: v1
kind: Secret
metadata:
  name: device-snapshot-secret
  namespace: kafkaworker
type: Opaque
data:
  db.username: "bWlhZG1pbg==" # miadmin
  db.password: "ZTVBa2k1TEpIbA==" # e5Aki5LJHl
