---
apiVersion: v1
kind: Secret
metadata:
  name: jasper-secret
type: Opaque
data:
  dbuser: "amFzcGVy" # jasper
  dbpass: "VVNwbkdIRjk4aw==" # USpnGHF98k
  polarisuser: "cmVwb3J0dXBsb2FkZXJAbW9iaWxlaXJvbi5jb20=" # reportuploader@mobileiron.com
  polarispass: "cG9sYXJpczEyMw==" # polaris123
  build.db.pw: "ZTVBa2k1TEpIbA==" # e5Aki5LJHl
