---
apiVersion: v1
kind: Secret
metadata:
  name: polaris-secret
type: Opaque
data:
  # BASE64 encoded
  encryption.key: "bDdDdk05S0ZsTHF6WVNMWDd6a2htRkJnajJtMFJqUUs2VmlpZTF1bkV4az0=" # l7CvM9KFlLqzYSLX7zkhmFBgj2m0RjQK6Viie1unExk=
  saml.ks.password: "cG9sYXJpczEyMw==" # polaris123
  polaris.db.password: "cG9sYXJpczEyMw==" # polaris123
  redis.auth_token: "NDFhNjFiNjZkM2ZkMWIyNzFlNjg0MGQ3MjQxOTBmMzA=" # 41a61b66d3fd1b271e6840d724190f30
  rpt.jdbc.password: "cG9sYXJpczEyMw==" # polaris123
  activemq.password: "c2VjcmV0" # secret
  jmx.secret: "QnU5QmZwdXk="    # Bu9Bfpuy
  # Only for migration
  cassandra.password: "cG9sYXJpczEyMw==" # polaris123
