apiVersion: v1
kind: Secret
metadata:
  name: reporting-secrets
type: Opaque
data:
  # BASE64 encoded
  admin_password: # Random generated password
  build_db_user: # miadmin or super user
  build_db_password: # miadmin db password
  dbUsername: cmVwb3J0aW5n #reporting db user(reporting)
  dbPassword: # Random generated reporting db password
  polarisDBUsername: cG9sYXJpcw== #polaris DB User(polaris)
  polarisDBPassword: # Polaris DB Password
  reporting_uploader_polaris_user: cmVwb3J0dXBsb2FkZXJAbW9iaWxlaXJvbi5jb20= # reportuploader@mobileiron.com
  reporting_uploader_polaris_pass:  #reportuploader@mobileiron.com password
  reporting_secrets: |-
    # Encoded secrets from reporting_secrets file.