---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jasper-upgrade-deployment
  labels:
    app: jasper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jasper
  template:
    metadata:
      labels:
        app: jasper
    spec:
      initContainers:
        - name: jasper-initdb-step-1
          image: ivantipartners/jasperreports:117.0.0-904.production
          command:
            - /mobileiron.com/run-k8s.sh
          securityContext:
            privileged: true
          env:
            - name: OPERATION
              value: INIT_DB
            - name: jdbc_host
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: dbhost
            - name: build_db_user
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: build.db.user
            - name: build_db_password
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: build.db.pw
            - name: build_db_name
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: build.db.name
            - name: jdbc_username
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: target.db.user
            - name: jdbc_password
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: dbpass
        - name: jasper-upgradedb-step1
          image: ivantipartners/jasperreports:117.0.0-904.production
          command:
            - /mobileiron.com/run.sh
            - upgradedb
          securityContext:
            privileged: true
          env:
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: dbhost
            - name: SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: dbsslmode
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: dbuser
            - name: DBPASS
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: dbpass
            - name: POLARISHOST
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: hostname
            - name: POLARISUSER
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: polarisuser
            - name: POLARISPASS
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: polarispass
          volumeMounts:
            - name: nfs-share-jasper
              mountPath: /mobileiron.com/data/java
        - name: jasper-export-step1
          image: ivantipartners/jasperreports:117.0.0-904.production
          command: ["/bin/sh", "-c"]
          args:
            - |
              /mobileiron.com/run.sh &
              sleep 100s
              echo "start backup js-6.1.0"
              cd /mobileiron.com/programs/com.jaspersoft.jasperserver/webapps/jasperserver/buildomatic \
              && cp ../WEB-INF/scripts/default_master.properties . \
              && chmod +x *.sh js-ant ../apache-ant/bin/ant \
              && ./js-ant export-everything-ce -DexportFile=/mobileiron.com/data/java/js-6.1.0-export.zip \
              && ls -l /mobileiron.com/data/java/
              echo "$?, end of 1-st step"
          env:
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: dbhost
            - name: SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: dbsslmode
            - name: MIN_HEAP_SIZE
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: min.heap
            - name: MAX_HEAP_SIZE
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: max.heap
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: dbuser
            - name: DBPASS
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: dbpass
            - name: POLARISHOST
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: hostname
            - name: POLARISUSER
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: polarisuser
            - name: POLARISPASS
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: polarispass
          volumeMounts:
            - name: nfs-share-jasper
              mountPath: /mobileiron.com/data/java
        - name: jasper-grant-permissions
          image: ivantipartners/jasperreports:117.0.0-904.production
          command: ["/bin/sh", "-c"]
          args:
            - |
              PGPASSWORD=${DB_PASSWORD} /usr/bin/psql -h ${DBHOST} -U ${DB_USER} -d ${JDBC_DB_NAME} -c "ALTER ROLE ${JDBC_USERNAME} WITH CREATEDB;"
              sleep 180s;
          env:
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: dbhost
            - name: JDBC_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: target.db.user
            - name: JDBC_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: target.db.name
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: build.db.user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: build.db.pw
        - name: jasper-upgradedb-step2
          image: ivantipartners/jasperreports:117.0.0-904.production
          command:
            - /mobileiron.com/run.sh
            - upgradedb
          securityContext:
            privileged: true
          env:
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: dbhost
            - name: SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: dbsslmode
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: dbuser
            - name: DBPASS
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: dbpass
            - name: POLARISHOST
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: hostname
            - name: POLARISUSER
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: polarisuser
            - name: POLARISPASS
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: polarispass
          volumeMounts:
            - name: nfs-share-jasper
              mountPath: /mobileiron.com/data/java
        - name: jasper-export-step2
          image: ivantipartners/jasperreports:117.0.0-904.production
          command: ["/bin/sh", "-c"]
          args:
            - |
              /mobileiron.com/run.sh &
              sleep 100s
              curl http://localhost:8080/jasperserver/rest_v2/serverInfo
              sh /mobileiron.com/programs/com.jaspersoft.jasperserver/webapps/jasperserver/WEB-INF/scripts/exportdb.sh \
              && ls -l /mobileiron.com/data/java/
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: dbhost
            - name: SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: dbsslmode
            - name: MIN_HEAP_SIZE
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: min.heap
            - name: MAX_HEAP_SIZE
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: max.heap
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: dbuser
            - name: DBPASS
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: dbpass
            - name: POLARISHOST
              valueFrom:
                configMapKeyRef:
                  name: jasper-configmap
                  key: hostname
            - name: POLARISUSER
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: polarisuser
            - name: POLARISPASS
              valueFrom:
                secretKeyRef:
                  name: jasper-secret
                  key: polarispass
          volumeMounts:
            - name: nfs-share-jasper
              mountPath: /mobileiron.com/data/java
      containers:
        - name: jasper-sleep
          image: ivantipartners/jasperreports:117.0.0-904.production
          command: ["/bin/sh", "-c"]
          args:
            - |
              ls /mobileiron.com/data/java
              echo "End of the first upgrade step."
              sleep 3600s
          volumeMounts:
            - name: nfs-share-jasper
              mountPath: /mobileiron.com/data/java
      volumes:
        - name: nfs-share-jasper
          persistentVolumeClaim:
            claimName: nfs-pvc-jasper
      imagePullSecrets:
        - name: docker-hub-secret
