---
apiVersion: v1
kind: ConfigMap
metadata:
  name: device-worker-configmap
  namespace: kafkaworker
data:
  indexer.name: "device-worker"
  kafka.worker.groupid: "devices_workers"
  kafka.worker.topics: "dbserver1.public.mdm_cdc"
  kafka.worker.failedtopic: "dbserver1.public.mdm_cdc_retry_failed"
  kafka.worker.retryfailedtopic: "dbserver1.public.mdm_cdc_retry_failed"
  kafka.worker.aliasnames: "{'MDM_CDC':'devices'}"
  kafka.worker.messagetoindextypes: "{'MDM_CDC':'MDM_CDC'}"
  kafka.ssl.enabled: "false"
  kafka.hosts: "kafka-0.cluster.datasvcs:9092,kafka-1.cluster.datasvcs:9092,kafka-2.cluster.datasvcs:9092"
  java.opts: "-Xmx768m -Xms512m"
  db.url: "jdbc:postgresql://postgres.cluster.datasvcs:5432/polaris?sslmode=disable"
  zookeeper.hosts: "zookeeper-0.cluster.datasvcs:2181,zookeeper-1.cluster.datasvcs:2181,zookeeper-2.cluster.datasvcs:2181"
  es.url: "http://elasticsearch-0.cluster.datasvcs:9200"
  es.replicas.number: "1"
  prefix: "''"
  reindex.kafka.topic.name: "<reindex_kafka_topic_name>"
  reindex.es.index.name: "<reindex_es_index_name>"
  device.custom.transformation.enabled: "true"
  account.custom.transformation.enabled: "false"
