---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret-dbmanager
  namespace: dbmanager
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogeyJhdXRoIjogImJXOWlhV3hsYVhKdmJtUnZZMnRsY21WNGRHVnlibUZzTVRVek9tUmphM0pmY0dGMFgyTTFWak5aZVV4Q1owdGtPVTQxUmpWaFoySTJkbXhwU21aVk1BPT0ifX19
  # decode base64-encoded value for the key .dockerconfigjson
  # {"auths": {"https://index.docker.io/v1/": {"auth": "bW9iaWxlaXJvbmRvY2tlcjQ3MDpkY2tyX3BhdF81aHdkR05tQ1ljZUtPX0p3Sy1XNEw2QlI5Zjg="}}}
  # decode base64-encoded value for the key auth
  # miuser:0f26ca1d-5845-466c-bb95-7fab7985be76
type: kubernetes.io/dockerconfigjson
