---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-audit-trail-worker
  namespace: kafkaworker
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mobileiron.com/data/audit-trail-worker/debug/
    server: nfs-server.cluster.datasvcs
  persistentVolumeReclaimPolicy: Retain
