---
docker_version: 23.0.6-1.el7
docker_install_compose: false
docker_login_required: true
userland_proxy: false
no_new_privileges: true
log_driver: fluentd
fluentd_address: '127.0.0.1'

aws_region: us-east-1
aws_profile: default
aws_account_id:
  "{{ lookup('aws_credentials', profile=aws_profile)['aws_account_id'] }}"
aws_access_key_id:
  "{{ lookup('aws_credentials', profile=aws_profile)['aws_access_key_id'] }}"
aws_secret_access_key:
  "{{ lookup('aws_credentials', profile=aws_profile)['aws_secret_access_key'] }}"
