---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-inventory-worker-configmap
  namespace: kafkaworker
data:
  indexer.name: "app-inventory-worker"
  kafka.worker.groupid: "app_inventory_workers"
  kafka.worker.topics: "dbserver1.public.mdm_cdc"
  kafka.worker.failedtopic: "dbserver1.public.app_inventory_failed"
  kafka.worker.retryfailedtopic: "dbserver1.public.app_inventory_retry_failed"
  kafka.worker.aliasnames: "{'APP_INVENTORY':'app_inventory'}"
  kafka.worker.messagetoindextypes: "{'MDM_CDC':'APP_INVENTORY'}"
  kafka.ssl.enabled: "false"
  kafka.hosts: "kafka-0.cluster.datasvcs:9092,kafka-1.cluster.datasvcs:9092,kafka-2.cluster.datasvcs:9092"
  java.opts: "-Xmx384m -Xms384m"
  db.url: "jdbc:postgresql://postgres.cluster.datasvcs:5432/polaris?sslmode=disable"
  zookeeper.hosts: "zookeeper-0.cluster.datasvcs:2181,zookeeper-1.cluster.datasvcs:2181,zookeeper-2.cluster.datasvcs:2181"
  es.url: "http://elasticsearch-0.cluster.datasvcs:9200"
  es.replicas.number: "1"
  prefix: "''"
  reindex.kafka.topic.name: "<reindex_kafka_topic_name>"
  reindex.es.index.name: "<reindex_es_index_name>"
  device.custom.transformation.enabled: "false"
  account.custom.transformation.enabled: "false"
