---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbmanager-configmap
  namespace: dbmanager
data:
  cloudops.dir: /mobileiron.com/programs/cloudops/
  rpt.dir: /mobileiron.com/data/cloudops/rpt/
  db.host: postgres.cluster.datasvcs
  db.port: "5432"
  db.username: polaris
  db.name: polaris
  db.sslmode: disable
  rpt.host: postgres.cluster.datasvcs
  rpt.port: "5432"
  rpt.login: polaris_rpt
  rpt.name: polaris_rpt
  rpt.sslmode: disable
  dbmanager.path: /mobileiron.com/data/dbmanager/
  slack.url.for.bloat.tables: "''"       # If doesn't set you'll see error at the end of the log, it's expected behavior.
  victorops.url.for.bloat.tables: "''"   # Example for Slack:"https://hooks.slack.com/services/T33A89WTG/A086375DFGH/HJUFCb9KgkBGCERTCX5MbLlL"
  bloat.threshold: "10737418240"         # Example for VICTOROPC: "https://alert.victorops.com/integrations/generic/53624209/alert/b42abc19-9888-3426-8f7f-6dc3c66647f/dbalerts-victorops"
  hostname: "somewhere"
